export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAILED = "ARTICLE_LIST_FAILED";
export const ARTICLE_LIST_RESET = "ARTICLE_LIST_RESET";


export const ARTICLE_DETAILS_REQUEST = "ARTICLE_DETAILS_REQUEST";
export const ARTICLE_DETAILS_SUCCESS = "ARTICLE_DETAILS_SUCCESS";
export const ARTICLE_DETAILS_FAILED = "ARTICLE_DETAILS_FAILED";
export const ARTICLE_DETAILS_RESET = "ARTICLE_DETAILS_RESET";


export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST";
export const ARTICLE_DELETE_SUCCESS = "ARTICLE_DELETE_SUCCESS";
export const ARTICLE_DELETE_FAILED = "ARTICLE_DELETE_FAILED";

export const ARTICLE_CREATE_REQUEST = "ARTICLE_CREATE_REQUEST";
export const ARTICLE_CREATE_SUCCESS = "ARTICLE_CREATE_SUCCESS";
export const ARTICLE_CREATE_FAILED = "ARTICLE_CREATE_FAILED";
export const ARTICLE_CREATE_RESET = "ARTICLE_CREATE_RESET";

export const ARTICLE_UPDATE_REQUEST = "ARTICLE_UPDATE_REQUEST";
export const ARTICLE_UPDATE_SUCCESS = "ARTICLE_UPDATE_SUCCESS";
export const ARTICLE_UPDATE_FAILED = "ARTICLE_UPDATE_FAILED";
export const ARTICLE_UPDATE_RESET = "ARTICLE_UPDATE_RESET";


export const LATEST_ARTICLES_REQUEST = "LATEST_ARTICLES_REQUEST";
export const LATEST_ARTICLES_SUCCESS = "LATEST_ARTICLES_SUCCESS";
export const LATEST_ARTICLES_FAIL = "LATEST_ARTICLES_FAIL";
export const LATEST_ARTICLES_RESET = "LATEST_ARTICLES_RESET";
