export const ARTICLE_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const ARTICLE_LIST_FAILED = "PRODUCT_LIST_FAILED";

export const ARTICLE_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const ARTICLE_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const ARTICLE_DETAILS_FAILED = "PRODUCT_DETAILS_FAILED";
export const ARTICLE_DETAILS_RESET = "PRODUCT_DETAILS_RESET";


export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST";
export const ARTICLE_DELETE_SUCCESS = "ARTICLE_DELETE_SUCCESS";
export const ARTICLE_DELETE_FAILED = "ARTICLE_DELETE_FAILED";

export const ARTICLE_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const ARTICLE_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const ARTICLE_CREATE_FAILED = "PRODUCT_CREATE_FAILED";
export const ARTICLE_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const ARTICLE_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const ARTICLE_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const ARTICLE_UPDATE_FAILED = "PRODUCT_UPDATE_FAILED";
export const ARTICLE_UPDATE_RESET = "PRODUCT_UPDATE_RESET";


export const LATEST_ARTICLES_REQUEST = "LATEST_ARTICLES_REQUEST";
export const LATEST_ARTICLES_SUCCESS = "LATEST_ARTICLES_SUCCESS";
export const LATEST_ARTICLES_FAIL = "LATEST_ARTICLES_FAIL";
export const LATEST_ARTICLES_RESET = "LATEST_ARTICLES_RESET";
