export const AUTHOR_CREATE_REQUEST = "AUTHOR_CREATE_REQUEST";
export const AUTHOR_CREATE_SUCCESS = "AUTHOR_CREATE_SUCCESS";
export const AUTHOR_CREATE_FAILED = "AUTHOR_CREATE_FAILED";
export const AUTHOR_CREATE_RESET = "AUTHOR_CREATE_RESET";

export const AUTHOR_LIST_REQUEST = "AUTHOR_LIST_REQUEST";
export const AUTHOR_LIST_SUCCESS = "AUTHOR_LIST_SUCCESS";
export const AUTHOR_LIST_FAILED = "AUTHOR_LIST_FAILED";
export const AUTHOR_LIST_RESET = "AUTHOR_LIST_RESET";

export const AUTHOR_DETAILS_REQUEST = "AUTHOR_DETAILS_REQUEST";
export const AUTHOR_DETAILS_SUCCESS = "AUTHOR_DETAILS_SUCCESS";
export const AUTHOR_DETAILS_FAILED = "AUTHOR_DETAILS_FAILED";
export const AUTHOR_DETAILS_RESET = "AUTHOR_DETAILS_RESET";

export const LATEST_ARTICLE_REQUEST = "LATEST_ARTICLE_REQUEST";
export const LATEST_ARTICLE_SUCCESS = "LATEST_ARTICLE_SUCCESS";
export const LATEST_ARTICLE_FAIL = "LATEST_ARTICLE_FAIL";
export const LATEST_ARTICLE_RESET = "LATEST_ARTICLE_RESET";