export const VIDEO_UPLOAD_REQUEST = "VIDEO_UPLOAD_REQUEST";
export const VIDEO_UPLOAD_SUCCESS = "VIDEO_UPLOAD_SUCCESS";
export const VIDEO_UPLOAD_FAILED = "VIDEO_UPLOAD_FAILED";
export const VIDEO_UPLOAD_RESET = "VIDEO_UPLOAD_RESET";

export const VIDEO_LIST_REQUEST = "VIDEO_LIST_REQUEST";
export const VIDEO_LIST_SUCCESS = "VIDEO_LIST_SUCCESS";
export const VIDEO_LIST_FAILED = "VIDEO_LIST_FAILED";
export const VIDEO_LIST_RESET = "VIDEO_LIST_RESET";


export const VIDEO_DETAILS_REQUEST = "VIDEO_DETAILS_REQUEST";
export const VIDEO_DETAILS_SUCCESS = "VIDEO_DETAILS_SUCCESS";
export const VIDEO_DETAILS_FAILED = "VIDEO_DETAILS_FAILED";
export const VIDEO_DETAILS_RESET = "VIDEO_DETAILS_RESET";

export const VIDEO_UPDATE_REQUEST = "VIDEO_UPDATE_REQUEST";
export const VIDEO_UPDATE_SUCCESS = "VIDEO_UPDATE_SUCCESS";
export const VIDEO_UPDATE_FAILED = "VIDEO_UPDATE_FAILED";
export const VIDEO_UPDATE_RESET = "VIDEO_UPDATE_RESET";

export const VIDEO_DELETE_REQUEST = "VIDEO_DELETE_REQUEST";
export const VIDEO_DELETE_SUCCESS = "VIDEO_DELETE_SUCCESS";
export const VIDEO_DELETE_FAILED = "VIDEO_DELETE_FAILED";