export const VIDEO_UPLOAD_REQUEST = "VIDEO_UPLOAD_REQUEST";
export const VIDEO_UPLOAD_SUCCESS = "VIDEO_UPLOAD_SUCCESS";
export const VIDEO_UPLOAD_FAILED = "VIDEO_UPLOAD_FAILED";
export const VIDEO_UPLOAD_RESET = "VIDEO_UPLOAD_RESET";

export const VIDEO_LIST_REQUEST = "VIDEO_LIST_REQUEST";
export const VIDEO_LIST_SUCCESS = "VIDEO_LIST_SUCCESS";
export const VIDEO_LIST_FAILED = "VIDEO_LIST_FAILED";